### ISSUE TITLE
aspnet core support?

### ISSUE THREAD

**Issue by bangonkali** [perrich/Hangfire.MemoryStorage#12]
Hi,

Are you planning to support asp net core 1.1/1.0?

**Comment by Symbianx** [comment]
The code seems to support .netstandard. But for some reason the mantainer has not pushed to NuGet yet.

**Comment by mrbart** [comment]
Looks like this could do it: https://www.nuget.org/packages/Hangfire.MemoryStorage.Core/

**Comment by perrich** [comment]
Hi, 
Sorry, I've not published the last version with .net core support.

**Comment by perrich** [comment]
Package is now available in nuget:
https://www.nuget.org/packages/Hangfire.MemoryStorage/
