### ISSUE TITLE
nuget package has netstandard1.4 minimum dependency instead of netstandard1.3

### ISSUE THREAD

**Issue by maximpashuk** [perrich/Hangfire.MemoryStorage#14]
Possible error in nuspec file

https://github.com/perrich/Hangfire.MemoryStorage/blob/master/Hangfire.MemoryStorage.nuspec#L22

target dir is netstandard1.4, but source dir is netstandard1.3

Because of this I cannot add Hangfire.MemoryStorage in project that targets netstandard1.3, get an error 

```
Package Hangfire.MemoryStorage 1.5.0 is not compatible with netstandard1.3 (.NETStandard,Version=v1.3). Package Hangfire.MemoryStorage 1.5.0 supports:
  - net40 (.NETFramework,Version=v4.0)
  - netstandard1.4 (.NETStandard,Version=v1.4)				
```

**Comment by perrich** [comment]
You've right. Thanks.

It's fixed in 1.5.1.
