### ISSUE TITLE
Re-use MemoryStorage as DictionaryStorage

### ISSUE THREAD

**Issue by felixg** [perrich/Hangfire.MemoryStorage#15]
From a shallow reading of the sources it seems that the only InMemory part are AutoIncrementIdGenerator and Data static classes in the Database directory. If so, then replacing them with any other Dictionary-like implementation will allow adding new storage back-ends with relatively minimal amount of work. For example, several key-value stores (e.g. ManagedEsent PersistentDictionary) provide such interface.

Am I correct in my assumption? I don't want to start this process, just to abandon it after the allotted time quota runs out.

**Comment by perrich** [comment]
Hi, 
It works because I've implemented Hangfire interfaces (like others databases implementations). 
If you only replace dictionaries by another implementation, yes it should work. But maybe you will have performance issues... So it depends on your needs.
