### ISSUE TITLE
Increasing process restarts for long jobs?

### ISSUE THREAD

**Issue by henkealg** [perrich/Hangfire.MemoryStorage#17]
Hi,
Thanks for a great addition to the Hangfire project. Sorry if this question has come up earlier. I did not find any answer in previous issues.
We are having issues with long jobs restarting 30 minute into the process using MemoryStorage. I suppose the FetchNextJobTimeout variable is used to control the timespan for restarts of jobs that seem "stale". Is there a way to increase this limit using a config option?

The project is running .net Core 2 on Ubuntu.

**Comment by perrich** [comment]
Hi,
Yes, it's available using MemoryStorageOptions :

```
var options = new MemoryStorageOptions();
options.FetchNextJobTimeout = TimeSpan.FromMinutes(60);

GlobalConfiguration.Configuration.UseMemoryStorage(options);
```

**Comment by henkealg** [comment]
Changing the options worked as a charm.
Thank you for the fast response. 👍 
Closing issue.
