### ISSUE TITLE
Production usage concerns?

### ISSUE THREAD

**Issue by avlcodemonkey** [perrich/Hangfire.MemoryStorage#27]
I'm looking at using MemoryStorage in a production system.  The readme suggests there are issues with thread safety and static data usage.  With the PR #26 the static Data problem is resolved now.  It looks like AutoIncrementIdGenerator may have a similar static issue.  What changes do you think are still needed to make it safe for production usage?

**Comment by perrich** [comment]
Hi,

In my point of view, Hangfire without a persistance layer is not a good idea for production.
I've created the memory storage as quick test purpose only, so I prefer to warn users. 

Static class is not an issue (depends on what you need to share or not). The PR #26 fixes impact in unit tests not in thread behavior.
