### ISSUE TITLE
Hangfire.Core Upgrade

### ISSUE THREAD

**Issue by SkinnySackboy** [perrich/Hangfire.MemoryStorage#34]
Hi @perrich have you got any objections if I open a PR to upgrade HangFire.Core to a more recent version, as currently there is a dependency on a version from over 3 years ago?

**Comment by perrich** [comment]
Hi, It should be a great thing!
I've kept an old version to allow near than any version with the plugin but it's not really needed.

**Comment by SkinnySackboy** [comment]
Ace thanks, I'll get cracking as soon as I can.

**Comment by SkinnySackboy** [comment]
I've opened PR #35

**Comment by perrich** [comment]
Thank you! Your PR have been merged.

**Comment by SkinnySackboy** [comment]
Thanks @perrich
