### ISSUE TITLE
Retention / Expiration of Data

### ISSUE THREAD

**Issue by janniksam** [perrich/Hangfire.MemoryStorage#36]
What is the retention / expiration set to when using the memory storage?
And can you override it?

I do only need to keep all my job information etc. for a few hours or maybe a day. Thats why I'd love to know, if the memory storage fills the memory until it reaches the servers capacity or if its limited to a timespan / max memory usage.

**Comment by perrich** [comment]
Hi, there is no limit/expiration by design.
