### ISSUE TITLE
Job states and parameters don't get removed when job are "expired"

### ISSUE THREAD

**Issue by fruffin** [perrich/Hangfire.MemoryStorage#4]
When the expiration manager runs, it doesn't dispose of the expired job states and job parameters.

I've had a look at the SQL Server provider but a quick glance doesn't show any obvious way of cleaning this up.
I'll make the change for the memory storage and submit a pull request in the next couple of days

**Comment by perrich** [comment]
Thank you in advance

**Comment by fruffin** [comment]
Done in this pull request:
https://github.com/perrich/Hangfire.MemoryStorage/pull/3
