### ISSUE TITLE
Is there an easy way to clear down storage between unit tests?

### ISSUE THREAD

**Issue by grahambunce** [perrich/Hangfire.MemoryStorage#44]
I'm using this to run my hangfire unit tests but jobs etc. are retained between test runs. I can manually delete jobs but it would cleaner if I could start with a fresh instance, or there is a quick way to remove all entries in the Data class.

My current thinking with the existing design is to use cast the JobStorage to the MemoryStorage class, use the GetEnumerable to get a list of keys and then Delete these manually with the Delete method.

Is this is preferred approach or am I missing something obvious?

Thanks

**Comment by perrich** [comment]
Hi, It's  good question.
Nothing really exists to do it.

Your workaround using MemoryStorage.Data seems good to remove old data.

**Comment by grahambunce** [comment]
For some reason that didn’t work either but I couldn’t work out why. For the benefit of others, what I ended up doing was as follows:

when you create a background server you can pass in a new memory store. Do this per test
You cannot use the static methods to create jobs. It will fail as job storage is not configured correctly. You can create a client though and set this up to use the same job store as the server.
If (like me) you are injecting dependencies them you should use the client interfaces, the V2 of which expose the job store for funky stuff 

I don’t that the code to hand to copy examples, but after much trail and error I got each test to be properly isolated with the above approach.
