### ISSUE TITLE
'Could not load file or assembly'

### ISSUE THREAD

**Issue by astrohart** [perrich/Hangfire.MemoryStorage#46]
I created a console app using .NET Framework 4.8 and installed `Hangfire.Core` v1.8.11.0, and `Hangfire.Autofac`, `Autofac`, and this package.

Everything builds, but then, upon execution, my app crashes with a `System.IO.FileNotFoundException`:

```
Could not load file or assembly 'Hangfire.Core, Version=1.7.35.0, Culture=neutral, PublicKeyToken=e33b67d3bb5581e4' or one of its dependencies.  The located assembly's manifest definition does not match the assembly reference. 
```

**Comment by perrich** [comment]
As it is written, the version are not compatible.
Have, you checked with the 1.7 version of Hangfire.Core ?
