### ISSUE TITLE
Support .NET Core v1

### ISSUE THREAD

**Issue by timfish** [perrich/Hangfire.MemoryStorage#5]
```
Package Hangfire.MemoryStorage 1.2.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Hangfire.MemoryStorage 1.2.0 supports: net45 (.NETFramework,Version=v4.5)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

**Comment by henkmollema** [comment]
Adding
```json
"imports": [
  "net45",
  "dotnet5.6",
  "portable-net45+win8"
]
```
to the `netcoreapp1.0` TFM will cause the package to resolve. However using it causes runtime exceptions. E.g.:
> 
Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

**Comment by henkmollema** [comment]
I'm crafting a PR with .NET Core support. In the mean while you could use this package which targets .NET Standard 1.3 (and .NET 4.5):
https://www.nuget.org/packages/Hangfire.MemoryStorage.Core
